In [10]:
from numpy import exp,dot,random,array

class NeuronLayer():
    def __init__(self,no_of_neurons,no_of_inputs_per_neuron):
        self.synaptic_weights = 2* random.random((no_of_inputs_per_neuron,no_of_neurons))
    
class NeuralNetwork():
    def __init__(self,layer1,layer2):
        self.layer1 = layer1
        self.layer2 = layer2
        
    #Sigmoid function
    def __sigmoid(self,x):
        return 1/(1+ exp(-x))

    #Derivative of sigmoid function
    def __sigmoid_derivative(self,x):
        return x*(1-x)

    #Training of neural network
    def train(self,training_set_inputs,training_set_outputs,train_iterations):
        for iteration in range(train_iterations):
                layer1_output,layer2_output = self.think(training_set_inputs)
                
                layer2_error = training_set_outputs - layer2_output
                layer2_delta = layer2_error * self.__sigmoid_derivative(layer2_output)
                
                layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
                layer1_delta = layer1_error * self.__sigmoid_derivative(layer1_output)
                
                layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
                layer2_adjustment = layer1_output.T.dot(layer2_delta)
                
                self.layer1.synaptic_weights += layer1_adjustment
                self.layer2.synaptic_weights += layer2_adjustment
                
    
    def think(self,inputs):
        layer1_output = self.__sigmoid(dot(inputs,self.layer1.synaptic_weights))
        layer2_output = self.__sigmoid(dot(layer1_output,self.layer2.synaptic_weights))
        return layer1_output,layer2_output
    
    def print_weights(self):
        print("Layer1: 4 neurons each with 3 inputs:")
        print(self.layer1.synaptic_weights)
        print("Layer2: 1 neuron with 4 inputs:")
        print(self.layer2.synaptic_weights)
        
if __name__ == "__main__":
    random.seed(1)
    layer1 = NeuronLayer(4,3)
    layer2 = NeuronLayer(1,4)
    neural_network = NeuralNetwork(layer1,layer2)
    print("Stage1: Random starting synaptic weights:")
    neural_network.print_weights()
    training_set_inputs = array([[0,0,1],[0,1,1],[1,0,1],[0,1,0],[1,0,0],[1,1,1],[0,0,0]])
    training_set_outputs = array([[0,1,1,1,1,0,0]]).T
    neural_network.train(training_set_inputs,training_set_outputs,60000)
    
    print("Stage 2: New synaptic weights after training:")
    neural_network.print_weights()
    
    print("Stage 3:Consider new situation [1,1,0]:")
    hidden_state,output = neural_network.think(array([1,1,0]))
    print(output)

Stage1: Random starting synaptic weights:
Layer1: 4 neurons each with 3 inputs:
[[  8.34044009e-01   1.44064899e+00   2.28749635e-04   6.04665145e-01]
 [  2.93511782e-01   1.84677190e-01   3.72520423e-01   6.91121454e-01]
 [  7.93534948e-01   1.07763347e+00   8.38389029e-01   1.37043900e+00]]
Layer2: 1 neuron with 4 inputs:
[[ 0.4089045 ]
 [ 1.75623487]
 [ 0.05477519]
 [ 1.34093502]]
Stage 2: New synaptic weights after training:
Layer1: 4 neurons each with 3 inputs:
[[ 6.47892716  5.3569066  -4.93989886  4.03848307]
 [-4.90353049  5.34871632  6.39687344  4.07017437]
 [ 0.78641328  0.04091763  0.85499938  1.69790731]]
Layer2: 1 neuron with 4 inputs:
[[-14.57942688]
 [ 12.05741367]
 [-14.58473645]
 [  8.18939311]]
Stage 3:Consider new situation [1,1,0]:
[ 0.02496571]
